// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DoAnWebApp.Models;

public partial class DonHang
{
    public string MaDh { get; set; }

    public string MaDangNhap { get; set; }

    public DateOnly NgayLap { get; set; }

    public int TrangThai { get; set; }

    public double TongThanhTien { get; set; }

    public string Sdt { get; set; }

    public string DiaChi { get; set; }

    public bool TrangThaiThanhToan { get; set; }
}